# This file was generated by GoReleaser. DO NOT EDIT.
cask "toney" do
  name "toney"
  desc "Toney - a fast, lightweight terminal-based note-taking app"
  homepage "https://sourcewarelab.github.io/Toney/"
  version "2.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toney"

  on_macos do
    on_intel do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "9afc22a69c18eb9d32cdd7b27e89ab2be2139f5cdcbe064b85181d06d006e183"
    end
    on_arm do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "f63aebd42fae62bb60dc57a38f522019e28cfacf943c4fad84c393a2882ed8ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "5e249feaa8933d999979621db03f4c7646b876054ec81b9f167429c57f52f956"
    end
    on_arm do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "f758d1f5e697bcc2578d3ddb6397eb16d3353088bde505171cfdb8e63e8c4f32"
    end
  end

  uninstall delete: [
      "/usr/local/bin/toney",
    ]

  # No zap stanza required
end
