# This file was generated by GoReleaser. DO NOT EDIT.
cask "toney" do
  name "toney"
  desc "Toney - a fast, lightweight terminal-based note-taking app"
  homepage "https://sourcewarelab.github.io/Toney/"
  version "2.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toney"

  on_macos do
    on_intel do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "04faa2eb31ac92bbfefde96bb8c5e386379d0b8de4c3ee71cbdc87a1a9e518c4"
    end
    on_arm do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "dd2ad5284465dec5fee5b1a287dd24b453dd5ea67e344aa142a3f3d8a59d2eb7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "4389eaa57551f55d18a7d4370ced8c7f9c0c1fe21cda07aad28a1c3e9b6ede1f"
    end
    on_arm do
      url "https://github.com/SourcewareLab/Toney/releases/download/v#{version}/toney_darwin_amd64.tar.gz"
      sha256 "c693a010212f8777240a28061cbcb079f2ef358727e93c1b3db9fe95fcad17ae"
    end
  end

  uninstall delete: [
      "/usr/local/bin/toney",
    ]

  # No zap stanza required
end
